User can click on business to view details
rrundle/Project-two pull request #11
Opened 2016-11-29 06:04 UTC by rrundle

2016-11-29 20:54 UTC, ronperris commented on search.html
> +    <a href="javascript:history.go(0);">
Don't inline JavaScript. Remove this.

2016-11-29 20:55 UTC, ronperris commented on search.js
> +function loadBusiness (businesses, id) {
Remove space after function name.

2016-11-29 20:56 UTC, ronperris commented on search.js
> +//event listener for click on any businesses
This should probably be one event listener, with a switch statement inside it.

2016-11-29 20:56 UTC, ronperris requested changes
Fix the commented areas.

2016-11-30 20:14 UTC, rrundle commented on search.html
> +    <a href="javascript:history.go(0);">
Done.

2016-11-30 20:14 UTC, rrundle commented on search.js
> +function loadBusiness (businesses, id) {
Done.

2016-11-30 20:14 UTC, rrundle commented on search.js
> +//event listener for click on any businesses
Done. One event listener with conditionals.

2016-12-01 02:13 UTC, merged