User can search for reviews by business details.
rrundle/Project-two pull request #8
Opened 2016-11-24 01:11 UTC by rrundle

2016-11-24 21:38 UTC, thebearingedge requested changes

2016-11-24 21:38 UTC, thebearingedge commented on search.js
> +  business.setAttribute("id", "business");
HTML `id` attributes should be unique page-wide. For styling, use a CSS class instead. For identification, use a unique value from your data model.
<img width="444" alt="screenshot 2016-11-24 13 35 03" src="https://cloud.githubusercontent.com/assets/7432943/20610186/f8dcded4-b24a-11e6-9475-e84910ead8a9.png">

2016-11-24 22:53 UTC, thebearingedge requested changes

2016-11-24 22:53 UTC, thebearingedge commented on search.js
> +//declaring function to search for matching text
Use meaningful function and parameter names instead of comments.

2016-11-26 05:31 UTC, rrundle commented on search.js
> +  business.setAttribute("id", "business");
Makes sense. Done.

2016-11-26 05:39 UTC, rrundle commented on search.js
> +//declaring function to search for matching text
changed function & variable names but left in comments for clarity.

2016-11-28 17:42 UTC, merged